### ISSUE TITLE
Update catalog for change to Cadastre and Land Tenure, hide info URLs

### ISSUE THREAD

**Issue by RacingTadpole** [TerriaJS/NorthernAustralia#11]
GA is currently updating the Cadastre and Land Tenure web services with data from a PSMA data release that occurred last week. We'll need to update the catalog for these changes.

We also need to hide links (URLs) in the metadata to web services that use third-party (PSMA) licensed data.

**Comment by axman6** [comment]
@RacingTadpole Can you let me know when you do this? We need to do the same on AREMI and I'll probably just crib from what you do.

**Comment by stevage** [comment]
Can you give me a bit more info @RacingTadpole ? Where is the new data?

**Comment by RacingTadpole** [comment]
@stevage - I've just forwarded you the email from GA. That's all the info I have. Do we need to get back to them for more?

**Comment by AnaBelgun** [comment]
Not a problem anymore.
