### ISSUE TITLE
Amend disclaimer terms & conditions

### ISSUE THREAD

**Issue by AnaBelgun** [TerriaJS/NorthernAustralia#123]
**Disclaimer and terms and conditions**
As a condition of using this website, users should understand and must accept, that the information and data provided on the Investor Map website:
•	is entirely dependent on the accuracy of the information and data which has been provided by the third party data custodians;
•	is not necessarily complete;
•	sometimes is general in nature; and
•	should not be relied on in place of independent research and professional advice.
Austrade and Data61 do not warrant, and are not liable for the accuracy of the information and data on the Investor Map website.

The information displayed on the Investor Map is for general informational purposes only, and is not intended to provide any commercial, financial, or legal advice. Any information in connection with the Investor Map may not be appropriate to your individual needs. You must exercise your own independent, skill, care and judgment with respect to how you use the information displayed on the Investor Map. As a condition of using the Investor Map, you must comply with all applicable laws, regulations and third party rights (including, without limitation, laws regarding the import or export of data or software, privacy and local laws). 
**See Full terms and conditions.**

I ACCEPT to replace OK

Text replacing Northern Australia with Investor Map terms and conditions
-----
Terms & Conditions
The information displayed on the Investor Map is for general informational purposes only, and is not intended to provide any commercial, financial, or legal advice. Any information in connection with the Investor Map may not be appropriate to your individual needs. You must exercise your own independent, skill, care and judgment with respect to how you use the information displayed on the Investor Map.
As a condition of using the Investor Map, you must comply with all applicable laws, regulations and third party rights (including, without limitation, laws regarding the import or export of data or software, privacy and local laws). You must not use the Investor Map to encourage or promote illegal activity or violation of third party rights. Some parts of the Investor Map (like the URL shortening function) rely upon third party APIs.
In any important matter, you should seek professional advice relevant to your own circumstances.
The information displayed on the Investor was consolidated by the Australian Trade and Investment Commission, and Data61.
The Australian Trade and Investment Commission, Data61 and Geoscience Australia (“We”) make no representations or warranties regarding the accuracy or completeness of any content or the product in connection with the Investor Map. We disclaim all responsibility and all liability (including without limitation, liability in negligence, for errors or omissions) for all expenses, loss, damage and costs which you might incur as a result of the information displayed on the Investor Map and your use of it.
The Investor Map must not be used for navigation or precise spatial analysis or for any activities where the use or failure of the Investor Map could lead to death, personal injury, or environmental damage (such as the operation of nuclear facilities, air traffic control, or life support systems).
Access to data:
Any information provided by data custodians displayed on the Investor Map is provided as is and on the understanding that the respective data custodian is not responsible for, nor guarantees the timeliness, accuracy or completeness of that information. If you intend to rely on any information displayed on the Investor Map, then you must apply in writing to the respective data custodian for further authorisation.
You acknowledge that your use of the Investor Map means that you have provided your acceptance of these terms and conditions.
You must consider the usage rights and restrictions of the base map and each activated dataset when using the output of the Investor Map in broadcast, print, or other distribution. The terms of use of the default Bing Maps base map may be found here: https://www.microsoft.com/maps/product/terms.html

**Comment by steve9164** [comment]
Disclaimer updated in #162. Will update Terms with about page.
