### ISSUE TITLE
Geology and Climate -> QLD: Wind gusts greater than 75 kph doesn't work

### ISSUE THREAD

**Issue by kring** [TerriaJS/NorthernAustralia#13]
![image](https://cloud.githubusercontent.com/assets/924374/20080118/243f82b8-a59c-11e6-9177-3dfcd363605d.png)

**Comment by kring** [comment]
`Geology and Climate -> Rainfall -> QLD: Frequency of rainfall filling dams - events per year` has the same problem.

**Comment by kring** [comment]
The two layers in `Existing projects -> Cropping` (both QLD layers) have the same problem.

**Comment by AnaBelgun** [comment]
Layer and category deleted from the latest version.
