### ISSUE TITLE
Add Australian Landscape Water Balance BoM services

### ISSUE THREAD

**Issue by AnaBelgun** [TerriaJS/NorthernAustralia#146]
Add the following to Climate group: 

Rainfall, month to date:
http://www.bom.gov.au/jsp/awra/thredds/wms/AWRACMS/deciles/month/rain_day.nc

Rainfall, year to date:
http://www.bom.gov.au/jsp/awra/thredds/wms/AWRACMS/deciles/year/rain_day.nc 

Add the following to Agriculture: 
Soil: 
Lower soil moisture, month to date:
http://www.bom.gov.au/jsp/awra/thredds/wms/AWRACMS/deciles/month/ss_pct.nc

Lower soil moisture, year to date: 
http://www.bom.gov.au/jsp/awra/thredds/wms/AWRACMS/deciles/year/ss_pct.nc

**Comment by steve9164** [comment]
Here's the rainfall "year to date" dataset: http://nationalmap.gov.au/northernaustralia/#share=s-o7VaI3NCCFyRNEGRROGFghzaB0T

It's hard to understand what is being visualised. The values are all between 0 and 1. Is there any metadata that could help with understanding the data? Without metadata it will be hard to configure the layers correctly.

**Comment by AnaBelgun** [comment]
@steve9164 please check this map top group of layers
here is an example: https://prototype.droughtmap.terria.io/#share=s-9UnHufG9Ud8jb2kggpUnC2eINw9

maybe this url is also helpful: http://www.bom.gov.au/jsp/awra/thredds/wms/AWRACMS/deciles/month/ss_pct.nc?service=WMS&version=1.3.0&request=GetCapabilities
