### ISSUE TITLE
Add Powerlines data service - GA

### ISSUE THREAD

**Issue by AnaBelgun** [TerriaJS/NorthernAustralia#153]
Add powerlines datalayer: 

http://services.ga.gov.au/gis/rest/services/NM_Culture_and_Infrastructure/MapServer

Currently in NationalMap: https://www.nationalmap.gov.au/#share=s-3v48OpXdJJaiS1cIXsHLOfnr5wv

**Comment by meh9** [comment]
@AnaBelgun is there some background to this? This duplicates the Transmission Lines layer but is not up to date and does not have colours - my advice is to not add this.

**Comment by AnaBelgun** [comment]
yes, they wanted both even though it was explained this hasn't been updated in a while. 
It had some data which is missing in the Transmission lines; it was communicated to GA and they updated the transmission lines, but client still wanted both.
