### ISSUE TITLE
Why does the Renewable Energy group direct user to AREMI?

### ISSUE THREAD

**Issue by RacingTadpole** [TerriaJS/NorthernAustralia#17]
![image](https://cloud.githubusercontent.com/assets/1757858/21085272/03eb8d76-c064-11e6-98c4-cd338a16979b.png)

@axman6, @kring - do either of you know why we set up Northern Australia's "Renewable Energy" catalog group to bring up an alert to go to AREMI instead? It would be much nicer if users could view AREMI datasets on the same map as their NorthernAustralian datasets. 

Is the AREMI catalog online like the NatMap one, and if so could we just link to it directly to always get the latest version?

**Comment by axman6** [comment]
Nothing to do with me, at least not that I remember. the AREMI catalog is online, but probably not in a way we could easily nest it? not sure how that works.

**Comment by AnaBelgun** [comment]
Hi Arthur. Some of the renewable layers on AREMI (e.g. Wind) are licensed specifically for the AREMI app, others are open data which can be copied (if necessary) on NA map. It would definitely improve the user experience. Another specific dataset which is licensed just for AREMI and in this case NA too, is the PSMA cadastre; we cannot show that data on NationalMap.

**Comment by AnaBelgun** [comment]
Fixed. NA map has now its own Renewables category with layers (copied) from AREMI.
