### ISSUE TITLE
Change Austrade logo and link

### ISSUE THREAD

**Issue by AnaBelgun** [TerriaJS/NorthernAustralia#19]

**Comment by AnaBelgun** [comment]
Please find attached the logo that should be used – essentially replace the Open for Business and AG crest logo with the attached lock-up instead.  I’ve attached both an eps (design) file and high res jpg.

I suggest the logo link to our Northern Australia page
http://www.austrade.gov.au/International/Invest/Opportunities/northern-australia

**Comment by steve9164** [comment]
Current branding:
![image](https://cloud.githubusercontent.com/assets/13863530/25517606/88b801a2-2c33-11e7-9bf4-a83ec4fee040.png)

New logos:
![ag-au-cmyk-80k_300dpi](https://cloud.githubusercontent.com/assets/13863530/25517567/6302fd40-2c33-11e7-809b-d39014988989.jpg)

EPS file:
[AG-AU-CMYK-80K.EPS.zip](https://github.com/TerriaJS/NorthernAustralia/files/963633/AG-AU-CMYK-80K.EPS.zip)

They want the 2 logos on the right hand side of the branding bar updated.

I'm guessing they still want white logos on an orange background but it's not clear. What do you think @AnaBelgun?

Maybe @philipgrimmett can look at using this to create a new branding bar image (or asking for those logos in a different colours/formats)?

**Comment by AnaBelgun** [comment]
Yeah, I think that too; if they wanted the orange background changed, they would have mentioned it. @philipgrimmett any ideas?

**Comment by AnaBelgun** [comment]
Hi @steve9164 is it possible to have the logo changes done (even only in prototype) before Monday's workshop? Please use the current background.

**Comment by AnaBelgun** [comment]
done
