### ISSUE TITLE
Implement designs for data default views

### ISSUE THREAD

**Issue by AnaBelgun** [TerriaJS/NorthernAustralia#20]
Client would like to see curated data sets lists for: 1)resources and energy; 2) agriculture and food; 3) tourism. 
There have been 2 options discussed so far:

- [ ] 3 curated data lists for displayed in the main catalogues sections, together with the current list of datastes, displayed under an "all data" subsection. 

- [ ] 3 new tabs, at the top of the preview page, next to 'Data catalogue' and "My data" existing tabs. The display of all datasets, in the current catalogue would remain unchanged (as another way for discovering data).

**Comment by philipgrimmett** [comment]
![namap-resourcesenergy](https://user-images.githubusercontent.com/5292858/28549781-f193007e-711f-11e7-8203-aa7c77c0f5bb.jpg)
![namap-rande-fullcatalogue](https://user-images.githubusercontent.com/5292858/28549888-8c3b2872-7120-11e7-947c-3a80b574b7bc.jpg)

**Comment by AnaBelgun** [comment]
![artboard copy 3](https://user-images.githubusercontent.com/18452161/28651346-b1f5f740-72c4-11e7-862f-363533d692dd.png)

**Comment by AnaBelgun** [comment]
Austrade has approved the new designs and would like them implemented in the prototype by 15th of October if possible. @steve9164 please assess the timeframe needed to have them done, so I can advise Austrade if 15th is not realistic.

**Comment by steve9164** [comment]
I'll need a couple of days to properly estimate the overall time. As well as implementing multiple catalogues in tabs, this would require restructuring the catalogue for Ag & Food and Tourism.

**Comment by meh9** [comment]
@steve9164 you may want to look at something similar that was worked on previously to see if it's useful (I guess otherwise it may be time to close that one off if we're not going to use it): https://github.com/TerriaJS/terriajs/pull/2353

**Comment by AnaBelgun** [comment]
done
