### ISSUE TITLE
Data update - Resources and energy

### ISSUE THREAD

**Issue by AnaBelgun** [TerriaJS/NorthernAustralia#21]
List of datasets to be included in the R&E default view/curated list. Temporarily, the R&E list will sit in the catalogue section at the top.

- [x] Add distinct group (first at the top, before Mining) land and tenure: tenure & title; add 4 layers (Native Title Determinations; Schedule of native titles determinations applications; Indigenous Land Use Agreements; RATSIB Areas)  from DGA Native Titles list: http://data.gov.au/dataset?organization=nationalnativetitletribunal&q=native+titles&sort=extras_harvest_portal+asc%2C+score+desc

- [ ] Add QLD land and tenure data available here: https://gisservices.information.qld.gov.au/arcgis/services/PlanningCadastre/LandUse/MapServer/WMSServer?request=GetCapabilities&service=WMS
**Broken service. Very slow responses and lots of 500 errors**

1) group name - **Mining**

- [x] Subgroup Soil - CSIRO Asris project - performance to be checked (layers work but they are slow, we should follow up with ASRIS to see if that can be fixed); sent performance report to Asris team on 26 Sep; 

- [x] Subgroup Surface geology  - to follow up with GA (broken links); requested updated urls from GA on 26 Sep; Updated service here: http://services.ga.gov.au/site_1/services/GA_Surface_Geology/MapServer/WMSServer?request=GetCapabilities&service=WMS

- [x] Subgroup Mineral occurrences; **rename subgroup Mineral Occurrences and  Resources** GA advised on 4 Oct to use: http://services.ga.gov.au/earthresource/ama/wms?request=GetCapabilities and http://services.ga.gov.au/earthresource/web/wicket/bookmarkable/org.geoserver.web.demo.MapPreviewPage?0 

- [ ] process the data under **Mineral Occurrences** - to show a better legend - currently all dots have the same colour; differentiate commodities as much as possible so the user can easily see location of a particular commodity 

- [x] **Mines & Mineral Deposits** to show a better legend - see above 

- [x] Remove **Major Resource Projects and Infrastructure** layer - outdated

- [ ] Subgroup Mine areas ; **rename subgroup Mines and Mining activity** **to add Mines and Mining Activity ** from http://services.ga.gov.au/earthresource/ama/wms?request=GetCapabilities and http://services.ga.gov.au/earthresource/web/wicket/bookmarkable/org.geoserver.web.demo.MapPreviewPage?0 

- [ ] Subgroup Mine areas: add QLD mining services available here http://qldspatial.information.qld.gov.au/catalogue/custom/search.page?q=mining:

-
 https://gisservices.information.qld.gov.au/arcgis/services/Boundaries/MiningAdministrativeAreas/MapServer/WMSServer?request=GetCapabilities&service=WMS

-
 https://gisservices.information.qld.gov.au/arcgis/services/Economy/MinesPermitsHistoric/MapServer/WMSServer?request=GetCapabilities&service=WMS

-
 https://gisservices.information.qld.gov.au/arcgis/services/Economy/MinesPermitsCurrent/MapServer/WMSServer?request=GetCapabilities&service=WMS

- [ ] Subgroup Mining tenements;  **to add Tenements (1 layer: Mineral Tenements)** from http://services.ga.gov.au/earthresource/ama/wms?request=GetCapabilities and http://services.ga.gov.au/earthresource/web/wicket/bookmarkable/org.geoserver.web.demo.MapPreviewPage?0

- [ ] Subgroup Operating mines QLD, NT, WA; **to delete the subgroup** - **to delete the QLD layer and move the current WA layer under Mines and Mining Activity** 

2. group name - **Oil & Gas**
all data under this group (from current NA map) - to be moved from Infrastructure - all currently working 
- no gas reserves data service as per email from GA on 4 Oct 17
- petroleum wells - http://services.ga.gov.au/geoserver/boreholes/wms?service=WMS&request=GetCapabilities 

cql_filter=WELLTYPE='Petroleum'

ie http://services.ga.gov.au/geoserver/boreholes/wms?SERVICE=WMS&VERSION=1.1.1&REQUEST=GetMap&FORMAT=image%2Fpng&TRANSPARENT=true&STYLES&LAYERS=boreholes%3ABoreholes&CQL_FILTER=WELLTYPE%3D%27Petroleum%27&SRS=EPSG%3A4283&WIDTH=768&HEIGHT=500&BBOX=65.91796875%2C-78.3984375%2C200.91796875%2C9.4921875

- oil platforms: http://services.ga.gov.au/site_9/services/Oil_Gas_Infrastructure/MapServer/WMSServer?request=GetCapabilities&service=WMS

- no gas reserves web service

3. group name - **Renewable energy** 
- [ ] Solar - to follow up with BoM for licensing; Checked with BoM (Andre Zerger on 4 Oct) and Solar services are ok to include (CC license); available here: http://neii.bom.gov.au/services/solarclim/catalog.html  
- [ ] Wind - to follow up with DNV GL; to use the AREMI 100m height layer 
- [x]  Bioenergy - to copy all AREMI layers
- [x] Wave - to copy all AREMI layers
- [x] Geothermal - to copy all AREMI layers
- [x] Hydro - to copy all AREMI layers

4. group name - **Infrastructure**

4.1 Electricity 
- [x] Electricity transmission lines (on NA map) - working
- [x] Distance to transmission lines - to copy from AREMI
- [x] Substations - to copy from AREMI
- [x] Distance to transmission substations - to copy from AREMI
- [ ] WA electricity infrastructure - included but needs user/pass for the WA SLIP service - pending approval from WA Gov

4.2 Transport (all data currently on NA map) 
4.2.1 Air 
- [x] Airports and airfields
- [x] Major airports
4.2.2. Land
- [x] all weather roads
- [x] key freight routes
- [ ] NT stock routes - to check why not working 
- [x] railways
- [x] road bridges and fords
4.2.3 Sea 
- [x] major seaports

5. Demography

- [ ] add Residential Population Density from GA: http://services.ga.gov.au/site_9/rest/services/NEXIS_Residential_Population_Density/MapServer

- [ ] Census data - available on AREMI from ABS
![image](https://user-images.githubusercontent.com/18452161/31413544-7b25d64a-ae65-11e7-8b60-9c8814587435.png)

**Comment by steve9164** [comment]
http://prototype-northernaustralia.terria.io/ updated to match requirements.

Changes are on `new_catalog` branch.

**Comment by AnaBelgun** [comment]
Austrade has asked to reorder the R&E catalogue as follows: 

1. Land and Tenure
2. Mining

- [ ] 2.1 Mineral Occurrences  (layer); delete Mineral Processing Plants and Mineral Processing Plants

- [ ] 2.2 Rename Mines and Mineral Deposits = Mines Operating Status

- [ ] 2.3 Rename Mineral Deposits = Mines and Mineral Deposits

- [ ] 2.4 Move here WA: Mines and Mineral deposits

- [ ] Delete Mines and Mining Activity entirely (including its two layers)

- [ ] Delete Mining tenements category but keep the two layers 

- [ ] 2.5 Keep NT Mining tenements

- [ ] 2.6 keep WA Mining Tenements

- [ ] Delete Operating Mines category but keep the WA layer and move it up as 2.4

**Comment by steve9164** [comment]
prototype updated with rearranged R&E catalogue

**Comment by AnaBelgun** [comment]
All data requested and available at the time of launch (11 Nov 2017) has been added. 
In phase 2A, if new energy & resources data will be requested, a new issue is submitted.
