### ISSUE TITLE
Data update - Tourism 

### ISSUE THREAD

**Issue by AnaBelgun** [TerriaJS/NorthernAustralia#25]
Include the following subgroups of data sets: 

**Tourism**

- [x] add data descriptions for each individual layer 

- Accommodation - all data from ABS: http://www.abs.gov.au/AUSSTATS/abs@.nsf/DetailsPage/8635.02015-16?OpenDocument 

- [x] Tourist accommodation Australia, All states and territories, 2015-2016  
[2015-2016 Tourist accomm All states.xlsx](https://github.com/TerriaJS/NorthernAustralia/files/1335398/2015-2016.Tourist.accomm.All.states.xlsx)

- [x] Tourist accommodation NT, 2015-2016, by Tourism Region - tables 10-13 under Data Cubes Tourist Accommodation, Small Area Data - NT 
[2015-2016 Tourist accomm small area NT.xlsx](https://github.com/TerriaJS/NorthernAustralia/files/1343238/2015-2016.Tourist.accomm.small.area.NT.xlsx)

- [x] Tourist accommodation WA, 2015-2016, by Tourism Region - tables 10-13 under Data Cubes Tourist Accommodation, Small Area Data - WA
[2015-2016 Tourist accomm small area WA.xlsx](https://github.com/TerriaJS/NorthernAustralia/files/1335401/2015-2016.Tourist.accomm.small.area.WA.xlsx)

- [x] Tourist accommodation QLD, 2015-2016, by Tourism Region - tables 10-13 under Data Cubes Tourist Accommodation, Small Area Data - QLD
[2015-2016 Tourist accomm small area QLD.xlsx](https://github.com/TerriaJS/NorthernAustralia/files/1335403/2015-2016.Tourist.accomm.small.area.QLD.xlsx)
 
**Visitors** - all data from Austrade
https://www.tra.gov.au/Research/International-visitors-to-Australia/international-visitor-survey-results
All tables: 
[2016-2017 Visitors all tables.xlsx](https://github.com/TerriaJS/NorthernAustralia/files/1335427/2016-2017.Visitors.all.tables.xlsx)
[2016-2017 Domestic visitors all tabless.xlsx](https://github.com/TerriaJS/NorthernAustralia/files/1335440/2016-2017.Domestic.visitors.all.tabless.xlsx)

- [x] International visitors

- Visitor nights and regional expenditure, 2016-2017, All States and territories - table 4; break down in 3 sheets and keep all variables (on the left)
[2016-2017 Visitors by State and reason.xlsx](https://github.com/TerriaJS/NorthernAustralia/files/1335430/2016-2017.Visitors.by.State.and.reason.xlsx)

- Visitor nights and regional expenditure by top 50 tourism regions - table 9a - don't include averages columns
[2016-2017 Visitors by State and reason top 50 tourism regions.xlsx](https://github.com/TerriaJS/NorthernAustralia/files/1335431/2016-2017.Visitors.by.State.and.reason.top.50.tourism.regions.xlsx)

- [x] Domestic visitors
- visitors by State and reason, 2016-2017 - table 1a
[2016-2017 Domestic visitors by State and reason.xlsx](https://github.com/TerriaJS/NorthernAustralia/files/1335443/2016-2017.Domestic.visitors.by.State.and.reason.xlsx)

- visitors by State and reason top 50 tourism regions - table 10
[2016-2017 Domestic visitors by State and reason top 50 tourism regions.xlsx](https://github.com/TerriaJS/NorthernAustralia/files/1335442/2016-2017.Domestic.visitors.by.State.and.reason.top.50.tourism.regions.xlsx)

- [x] LGA Tourism profiles 
https://www.tra.gov.au/tra/2016/Tourism_in_Local_Government_Areas_2016/LGA_Profiles/index.html#about 

- [x] add LGA boundaries 2016 to region mapping server

- [ ] add LGA population 

- [x] add LGA key metrics - 4 layers: International, Domestic overnight, Domestic day, Total

- [x] add LGA tourism businesses

- [x] add LGA tourism accommodation - 2 layers: domestic and international

- [x] add LGA tourism by reason - 2 layers: dom and intl

- [x] add LGA tourism by travel party - 2 layers: dom and intl

- [x] add LGA builder 2016 - IVS Country 

 **Infrastructure** (as for R&E group)

Electricity 

- [ ] Electricity transmission lines
- [ ] Distance to transmission lines 
- [ ] Substations
- [ ] Distance to transmission substations 
- [ ] WA electricity infrastructure - included but needs user/pass for the WA SLIP service

Transport (all data currently on NA map) 

Air 
- [ ] Airports and airfields
- [ ] Major airports

Land
- [ ] all weather roads
- [ ] key freight routes
- [ ] railways
- [ ] road bridges and fords

Sea 
- [ ] major seaports

**Demography** (Census 2011, as shown on AREMI)

- [ ] Add Residential Population layer from GA: http://services.ga.gov.au/gis/rest/services/NEXIS_Residential_Population_Density/MapServer 

![image](https://user-images.githubusercontent.com/18452161/31413522-5fafc830-ae65-11e7-8997-62556a9beead.png)

**Environmental** (all on AREMI)

- [ ] Australian World Heritage Areas
- [ ] CAPAD
- [ ] CHL
- [ ] NHL
- [ ] Conservation management zones
- [ ] DIWA
- [ ] EPBC referrals
- [ ] Key ecological features
- [ ] Ramsar upstream catchments
- [ ] Ramsar wetlands of international importance

**Climate** 

- [ ] Temperature - waiting for licensing and price from BoM (27 Sep)
- [ ] Rainfall - as above

**Comment by steve9164** [comment]
International Visitor Survey should use 2016 Tourism Regions, which are not implemented in nationalmap/northernaustraliamap yet

**Comment by AnaBelgun** [comment]
@steve9164 Tourism layers reordering and renaming: 

- [ ] delete the category Tourism data by LGA without deleting the layers

- [ ] rename the Tourist Accommodation = Tourist Accommodation and other key metrics

under the TRA Tourism data by LGA: 

- [ ] Rename TRA_IVS_Country_VisitorNights.csv = International visitor nights by country 2009-13 (LGA) and move at the bottom in the International Visitors category

- [ ] rename TRA_IVS_Country_Visitors.csv = International visitors by country 2009-13 (LGA) and move under International 

- [ ] TRA_accommodation_Domestic Overnight.csv = Accomm domestic visitors overnight 2009-13 (LGA) and move under Domestic

- [ ] TRA_accommodation_International.csv = Accomm international visitors 2009-13 (LGA) and move under International

- [ ] TRA_accommodation_Total.csv = Accomm total 2009-13 (LGA) and move under Accommodation and other key metrics

- [ ] TRA_key metrics_Domestic Day.csv = Key metrics domestic visitors 2009-13 (LGA) and move under Domestic

- [ ] TRA_key metrics_Domestic Overnight.csv = Key metrics domestic visitors overnight 2009-13 (LGA) and move under Domestic

- [ ] TRA_key metrics_International.csv = Key metrics international visitors 2009-13 (LGA) and move under International

- [ ] TRA_key metrics_Total.csv = Key tourism metrics 2009-13 (LGA) and move under the Accommodation and other key metrics

- [ ] TRA_reason_Domestic Day.csv = Domestic day visitors by reason 2009-13 (LGA) and move under Domestic

- [ ] TRA_reason_Domestic Overnight.csv = Domestic overnight visitors by reason 2009-13 (LGA) and move under Domestic

- [ ] TRA_reason_international.csv = International visitors by reason 2009-13 (LGA) and move under International

- [ ] TRA_reason Total.csv = Total visitors by reason 2009-13 (LGA) and move under Accommodation and other key metrics

- [ ] TRA_tourism_businesses.csv = Total tourism businesses 2009-13 (LGA) and move under Accommodation and other key metrics

- [ ] TRA_travel_party_Domestic Overnight.csv = Domestic visitors by travel party 2009-13 (LGA) and move under Domestic

- [ ] TRA_travel_party_International.csv = International visitors by travel party 2009-13 (LGA) and move under International

- [ ] TRA_travel_party_Total.csv = Total visitors by travel party 2009-13 (LGA) and move under Accommodation and other key metrics

**Comment by steve9164** [comment]
also updated on prototype

**Comment by AnaBelgun** [comment]
Should new tourism data be requested for Phase 2A, a new issue will be submitted.
