### ISSUE TITLE
Remove WA ILUA layer

### ISSUE THREAD

**Issue by stevage** [TerriaJS/NorthernAustralia#3]
It used Google Maps Engine.

**Comment by kring** [comment]
There's a similar (maybe equivalent?) on this WMS server, called Native Title (ILUA) (LGATE-067) (29-02-2016 00:35:04) (`LGATE-067`):
https://www2.landgate.wa.gov.au/ows/wmspublic

You'll need a username/password to access it, which you can get here:
https://www2.landgate.wa.gov.au/web/guest/request-registration-type

Rumor has AREMI already has permission to provide access to this (or similar?) server transparently, without requiring each user to register and log in, so perhaps NA can do the same.

**Comment by stevage** [comment]
We should add http://catalogue.beta.data.wa.gov.au/dataset/native-title-ilua-lgate-067

**Comment by AnaBelgun** [comment]
removed.
