### ISSUE TITLE
Catalogue jumping 

### ISSUE THREAD

**Issue by AnaBelgun** [TerriaJS/NorthernAustralia#30]
On the http://prototype-northernaustralia.terria.io/, once you click on a data subgroup under a tab (Resources and Energy, Tourism), the view jumps to an All Data catalogue view. If you click again on the particular tab initially selected, the catalogue under that tab is shown correctly; the "jumping" is repeated every time you click on a sub-group under Resources & Energy and Tourism tabs.

**Comment by steve9164** [comment]
Steps to fix catalogue tabs:
- Fix indexing of tabs inside explorer panel component
- Don't display normally hidden tabs (like user content or whatever)
- Call appropriate "group opened" and "group closed" events when navigating between tabs
- Display description of a tab when a tab is selected

**Comment by steve9164** [comment]
Fixed!
