### ISSUE TITLE
NA Map R2 (2017-11-09) pre-release test - Error running Analysis Tools - 1 (Wave Atlas)

### ISSUE THREAD

**Issue by EhsanCanberra** [TerriaJS/NorthernAustralia#39]
Error running analysis tool

Renewable Energy/Wave/Australian Wave Energy Atlas/Analysis Tools/Annual Bivariate Probability Distribution

![slide11](https://user-images.githubusercontent.com/22827786/32645992-4b88e9ae-c63e-11e7-94a6-b677923aa0ae.JPG)

**Comment by AnaBelgun** [comment]
Custodian notified. Known fragility of services.
