### ISSUE TITLE
NA Map R2 (2017-11-09) pre-release test - Error running Analysis Tool - 2 (Wave Atlas)

### ISSUE THREAD

**Issue by EhsanCanberra** [TerriaJS/NorthernAustralia#40]
Error running analysis tool

Renewable Energy/Wave/Australian Wave Energy Atlas/Analysis Tools/Monthly Bivariate Probability Distribution

![slide12](https://user-images.githubusercontent.com/22827786/32646026-89421cb6-c63e-11e7-900f-3acf5e5efd27.JPG)

**Comment by AnaBelgun** [comment]
Custodian notified. Known fragility of services.
