### ISSUE TITLE
NA Map R2 (2017-11-09) pre-release test - Error loading data layer - 6 (WA Electricity)

### ISSUE THREAD

**Issue by EhsanCanberra** [TerriaJS/NorthernAustralia#41]
Error loading data -> Authentication Required?

- Infrastructure/Electricity/Western Australia/Distribution Lines

![slide13](https://user-images.githubusercontent.com/22827786/32646095-ece1e594-c63e-11e7-844a-dc989387ac06.JPG)

**Comment by AnaBelgun** [comment]
@steve9164 please remove the WA Electricity group for this phase

**Comment by AnaBelgun** [comment]
Layer to be removed.
