### ISSUE TITLE
Redesign & develop Feedback button functionality for the Northern Australia Map

### ISSUE THREAD

**Issue by AnaBelgun** [TerriaJS/NorthernAustralia#55]
Update Feedback functionality to enable users to:
-Provide feedback about the application 
-Contact Austrade for more information on opportunities

**Comment by AnaBelgun** [comment]
Contact Austrade email for the moment: northernaustralia@austrade.gov.au 
Click on 
Contact Austrade

(and get)

![na feedback text1](https://user-images.githubusercontent.com/18452161/40892777-5c3fdf40-67de-11e8-9486-83edd4e94f8e.JPG)

If you would like an Austrade representative to contact you to discuss Australia’s  investment and business potential please provide your details below.  

Name*
 
Organisation*
 
Email address*
 
Country
Any comment:                                                                                                     
Mandatory fields marked with *


Map feedback

If you would like to provide feedback on your map experience to the software developers below please do so below.
If you are commenting on the actual data on the map, please consider sending your comments to the custodian of the dataset you're viewing, instead of using this form. Contact information for most datasets can be found by clicking "About this Data Set".



 





-------------------------------------
Give feedback tab
![na feedback text2](https://user-images.githubusercontent.com/18452161/40892783-71efd674-67de-11e8-8d32-1fef0565f856.JPG)

And the give feedback tab in bottom right hand corner needs to be renamed Contact Austrade, made  a bit larger, different colour and put in a more prominent position .

**Comment by AnaBelgun** [comment]
Designs ready: https://invis.io/F2KDQD0TAKP#/301414247_terria_-_Empty_Workbench

**Comment by AnaBelgun** [comment]
Client confirmed on 5th of Nov that he wants to include changes to the feedback button in the launch release. 
Below are the amendments to the design proposed by @philipgrimmett 

Could Data61 prepare a Contact Austrade form as per instructions below (based on refining one of the draft designs you created).
For those who hit send their submissions should be directed to investormap@austrade.gov.au




**Make an investment enquiry** (to replace Request a consultation)
If you're a foreign investor planning to establish or expand your business operations in Australia, Austrade can provide you with professional assistance, free of charge


**Provide feedback** 
Provide feedback on your map experience to Austrade and the software developers.

REMOVE Alternatively contact……
![contact austrade](https://user-images.githubusercontent.com/18452161/48097413-ee2c6680-e26d-11e8-9ee9-32c8ef980260.png)

**Make an investment enquiry**  (to replace Request a consultation)
Please complete the form below and one of our specialists will help you open the doors to a country with unlimited investment potential.  (to replace existing text below).

Remove Alternatively you can contact..
![request a consultation](https://user-images.githubusercontent.com/18452161/48097427-fab0bf00-e26d-11e8-819a-b9300712dfa7.png)

**Feedback**

If you would like to provide feedback on your map experience to Austrade and the software developers or make any comments on the data please do so below. (replacing first par below). 

PLSE DELETE SECOND PAR “If you are…….Thank you”
![feedback](https://user-images.githubusercontent.com/18452161/48097465-0bf9cb80-e26e-11e8-972f-eebdcaf2b403.png)

**Comment by philipgrimmett** [comment]
Updated design prototype:
https://invis.io/N7KDQCYRHC8#/301414247_terria_-_Empty_Workbench

**Comment by AnaBelgun** [comment]
- discuss with client the feedback emailing solution @AnaBelgun

**Comment by AnaBelgun** [comment]
@chloeleichen replace the email address with investormap@austrade.gov.au
