### ISSUE TITLE
Add more National Native Title Tribunal (NNTT) data and reorganise land tenure catalogue

### ISSUE THREAD

**Issue by AnaBelgun** [TerriaJS/NorthernAustralia#58]
Please add from NNTT data services list https://nntt.maps.arcgis.com/home/item.html?id=2698667a86e54550b732174a71c3bc57: 

- [ ] Registered Native Title Bodies Corporate
https://services2.arcgis.com/rzk7fNEt0xoEp3cX/arcgis/rest/services/NNTT_Custodial_AGOL/FeatureServer/0 

- [x] Register of Native Title Claims
https://services2.arcgis.com/rzk7fNEt0xoEp3cX/arcgis/rest/services/NNTT_Custodial_AGOL/FeatureServer/7 

- [x] Catalogue
when we grab these we can delete the NT ILUA layer (which is replicated under the national LUA database) and regroup the land tenure data list so the native title/indigenous ones are together. So that current catalogue becomes: 

Land and Tenure
Native Title Determinations
Indigenous Land Use Agreements
Native Title Determination Outcomes
Schedule of Native title Determination Applications
Register of Native Title Claims
Registered Native Title Bodies Corporate
RATSIB Areas
Indigenous Protected Areas (from data.gov.au)
Freehold
Crown Land 
Pastoral lease
Reserves
Convertible lease
Other lease
Secondary tenure type

**Comment by steve9164** [comment]
Adding/removing/rearranging these now.

**Comment by AnaBelgun** [comment]
@steve9164 please remove the RNTBC until we find a way to make it faster

**Comment by AnaBelgun** [comment]
Re-opening this issue to investigate if the Registered Native Title Bodies Corporate layer can be obtained in a WMS format from NNTT and added to the map to improve performance. When added as is (Esri shape file) is very very slow (3-5 minutes loading). This is critical data layer for Austrade; to be used in a demonstration in Broome in May 2018.

**Comment by AnaBelgun** [comment]
NNTT advised they can't provide a WMS at this stage but they'll try using data.gov.au and its geoserver. 
Data resource has been updated on data.gov.au on 11 May 2018 and now there is a (fast) WMS provided: https://data.gov.au/dataset/registered-native-title-body-corporate-rntbc-areas/resource/5f3a043b-c7e6-42de-9e64-830f5a8f264e

**Comment by AnaBelgun** [comment]
@meh The link for adding the Registered Native Title Body Corporate (RNTBC): 
https://data.gov.au/geoserver/registered-native-title-body-corporate-rntbc-areas/wms?request=GetCapabilities
