### ISSUE TITLE
Add Minerals Exploration and Petroleum Exploration data

### ISSUE THREAD

**Issue by AnaBelgun** [TerriaJS/NorthernAustralia#60]
Add:

- [x] minerals explorations - http://stat.data.abs.gov.au/sdmx-json/dataflow/MINING_EXPLORATION 

- [x] petroleum exploration - http://stat.data.abs.gov.au/sdmx-json/dataflow/PETROLEUM_EXPLORATION

- [x] Water Use on Australian Farms

**Comment by steve9164** [comment]
Added
