### ISSUE TITLE
Add Homesteads data

### ISSUE THREAD

**Issue by AnaBelgun** [TerriaJS/NorthernAustralia#64]
Add: 

- [ ] http://services.ga.gov.au/site_7/rest/services/NM_Labelling_and_Boundaries/MapServer/23 (it looks like this one is working)

- [ ] http://services.ga.gov.au/site_7/rest/services/NM_Labelling_and_Boundaries/MapServer/24

**Comment by steve9164** [comment]
Both datasets work, but 24 only has imagery at high zoom levels. Waiting on which group to put these datasets in

**Comment by AnaBelgun** [comment]
I think we should add 23 instead of 24.
