### ISSUE TITLE
Add Oil and Gas pipelines and basins

### ISSUE THREAD

**Issue by AnaBelgun** [TerriaJS/NorthernAustralia#69]
Add only the Oil & Gas platforms from this service: 

- [ ] http://services.ga.gov.au/site_9/services/Oil_Gas_Infrastructure/MapServer/WMSServer?request=GetCapabilities&service=WMS

**Comment by AnaBelgun** [comment]
GA has sent for testing a service which includes the gas basins. Currently we can't filter and show just the public data. Ticket here: https://github.com/TerriaJS/terriajs/issues/2973

**Comment by kring** [comment]
@AnaBelgun where do the basins go and what should the layer be called?
