### ISSUE TITLE
Make Airports Runaways data more visible and add to NA Map

### ISSUE THREAD

**Issue by AnaBelgun** [TerriaJS/NorthernAustralia#72]
As currently coloured, the runways are difficult to distinguish. 
https://preprod.nationalmap.gov.au/#share=s-gm8VRGC5p4GV7W4sQSFpMUePGbX

Austrade would like to add this data to the NA Map. 

Comments from GA: 
We have looked at your request, and come up with the following.

1.	Colours hard to see - When the 7 Dynamic National Map web services were created, they were designed to work with and complement each other. Hence it was very difficult to choose bright colours like red, yellow; if you wanted to see all the symbology for each feature together. For example, red was used for roads, blue for drainage, yellow for power or gas lines. Whilst we realise that grey is not a great colour for base maps, we will re-address the colours in the web service migration into the new spatial data infrastructure (cloud based).
2.	Changing symbology of the existing web services – If the existing services must be used in the short term, the WMS services can be altered with a Styled Layer Descriptor (SLD).
3.	Difference between Landing Ground Points and Line features – We are going to examine this issue. This may be an issue with our data, we are checking data sources we have.
4.	csv-geo-au compliment CSV: We are discussing this with our Data Stewards board. I think this is a relatively new standard, we are discussing on making it standard for all our geospatial CSW.

**Comment by AnaBelgun** [comment]
To confirm with Austrade if this data needs to be added

**Comment by meh9** [comment]
Was this data additional or was it meant to replace the existing Airports and Airfields layer?

**Comment by AnaBelgun** [comment]
In addition, but because of the very light colouring it was postponed until we/GA improve it. 
The data is Airport_Runway_Centrelines_and_Landing_Grounds_Line_Features (3)
