### ISSUE TITLE
Add BoM Climate data (temp, rainfall) from DoEE SoE 

### ISSUE THREAD

**Issue by AnaBelgun** [TerriaJS/NorthernAustralia#74]
Add climate data (Avg temperatures and rainfall) from BoM. Following consultation between Data61, BoM and Austrade, work on one of the following options: 

- [ ] Option 1 - built services for temp and rainfall, based on the historical BoM data; investigate with BoM if real time data can be provided 

- [ ] Option 2 - purchase the data, host and include it on the NA map

- [x] Option 3 - following confirmation with custodian, add the existing temp and rainfall data services (with data up to 2015) from the DoEE (https://soe.terria.io/) available on the SoE map and Data.gov.au

Rainfall services: 
![image](https://user-images.githubusercontent.com/18452161/38845189-ea6b6764-4239-11e8-97a5-54c654482d07.png)

Temperature: 
![image](https://user-images.githubusercontent.com/18452161/38845231-07934370-423a-11e8-9974-8b13b18b1613.png)

**Comment by meh9** [comment]
For Rainfall exclude Lake Eyre, for Temp exclude Reef.

**Comment by AnaBelgun** [comment]
@kring please add these layers in All Data only - under a new Section "Climate" with 2 subsections: "Temperature" and "Rainfall"
