### ISSUE TITLE
Investigate if removal of the SA levels with no data is possible - ABS data 

### ISSUE THREAD

**Issue by AnaBelgun** [TerriaJS/NorthernAustralia#75]
Ideally users would only have the SA levels with data shown. 
See example below with SA2 and SA3 not having any data. Austrade is suggesting to show just the geographical levels with data. 
http://nationalmap.gov.au/northernaustralia/#share=s-n7CGCcrrK9oUjDSB96JJyHCygqn

**Comment by meh9** [comment]
Some dev to be done, we'd have to try the other SA levels etc to see if they 404's, unless there is some kind of index around that says what is available.

**Comment by kring** [comment]
I'm looking at this one.
