### ISSUE TITLE
Fix the broken Bioenergy layers 

### ISSUE THREAD

**Issue by AnaBelgun** [TerriaJS/NorthernAustralia#79]
The national Bioenergy layers on NA Map do not work, but they're ok on AREMI. 

![image](https://user-images.githubusercontent.com/18452161/39344901-a954703a-4a28-11e8-8aff-ca9f7e2149fd.png)

Errors on NA Map: 

![image](https://user-images.githubusercontent.com/18452161/39344915-be3ab31a-4a28-11e8-89e7-9ae2945c30f2.png)

![image](https://user-images.githubusercontent.com/18452161/39344922-ca44c45c-4a28-11e8-8233-25960a4db86b.png)

**Comment by steve9164** [comment]
This is a CORS issue. We need to add `"biogas.nceastg.usq.edu.au"` to northernaustralia's `allowProxyFor` list. This will be done differently depending on when northernaustralia is separated from nationalmap.

**Comment by steve9164** [comment]
Looks like partially CORS, partially AREMI catalogue change. I'll update the AREMI catalogue so we get the new URLs for all the biogas datasets.

**Comment by kring** [comment]
@AnaBelgun I see I'm assigned to this, but is there anything I need to do? It just needs a new deployment, right?

**Comment by AnaBelgun** [comment]
I think so. I've asked @meh9 to have a look, as part of updating the whole renewables category in the NA Map (from AREMI).
