### ISSUE TITLE
Update Renewables category from AREMI

### ISSUE THREAD

**Issue by steve9164** [TerriaJS/NorthernAustralia#82]
AREMI's Renewables category has been updated with new biogas URLs (and more).

To bring northernaustralia up to date with AREMI we need to:
- [x] ensure licence compatibility of new datasets
- [x] build the latest (or latest tagged) AREMI catalogue and replace `datasources/shared/aremi.json`
- [x] exclude any new datasets that we can't include in northernaustralia
- [x] ensure that previously excluded datasets are still excluded (if they have moved in the AREMI catalogue)

The AREMI catalogue in use in northernaustralia is from August 2017 so the relevant part of the AREMI catalogue changelog is from [here](https://github.com/TerriaJS/aremi-natmap/blob/master/Changelog.md#version-2017-09-22) up.

Needed for #79.

**Comment by AnaBelgun** [comment]
Apart from the wind data (which should be the same as now on NA Map), everything else in AREMI Renewables category is fine to publish in the NA Map.

**Comment by meh9** [comment]
Merged in #94
