### ISSUE TITLE
Investigate and update (if possible) WA mining data layers - 404 error

### ISSUE THREAD

**Issue by AnaBelgun** [TerriaJS/NorthernAustralia#84]
Currently when user is trying to access the WA mining tenements and mining deposits, a 404 error is thrown. 
It might be a problem due to SLIP authentication we forgot to update (fix). not sure. 

![na map error 404](https://user-images.githubusercontent.com/18452161/39609376-e5c028ee-4f8b-11e8-971a-6851b5a9074e.png)

**Comment by AnaBelgun** [comment]
If we can't fix the error, the WA Mining layers should be removed.

**Comment by AnaBelgun** [comment]
This one has been surpassed by the Catalogue changes proposed by Austrade https://github.com/TerriaJS/NorthernAustralia/issues/90  
Will close.

**Comment by meh9** [comment]
Fixed by https://github.com/TerriaJS/NorthernAustralia/issues/90
