### ISSUE TITLE
Can't view Transmission lines in 2D

### ISSUE THREAD

**Issue by AnaBelgun** [TerriaJS/NorthernAustralia#85]
User cannot view the Transmission lines data in 2D anylonger. 

![na map 2d error](https://user-images.githubusercontent.com/18452161/39609436-4356d660-4f8c-11e8-9a60-324ff2d751f8.png)

**Comment by meh9** [comment]
NA (and maybe NM?) needs the same update AREMI just did to the TransLines.

**Comment by AnaBelgun** [comment]
@meh9 Do we have time to do it this sprint?

**Comment by meh9** [comment]
Fixed in latest AREMI catalogue which is now integrated.
