### ISSUE TITLE
May release - catalogue update

### ISSUE THREAD

**Issue by AnaBelgun** [TerriaJS/NorthernAustralia#90]
According to customer request (11 May 2018): 

Mining: 
- [x] Remove WA: Mines and Mineral deposits 

- [x] Remove WA: mining tenements 

- [x] Remove NT: mining tenements

Renewables: 

- [x] rearrange all geothermal layers / category: move the national layers at the top and create a NSW sub-category to include the NSW layers

- [x] provide instructions on how to use the Wave Atlas layers (on the blank page of the category)

- [x] reorganise the Bioenergy layers as per AREMI categorisation (national layers at the top)

- [x] under Hydro: check the River regions and if they don't work, remove 

Oil and Gas:

- [x] remove the NT layers: Gas pipelines and Oil pipelines

- [x] remove File Notation Area

- [x] rename Mindex - WA Mindex and move to Mining section

- [x] remove Mineral Drill Holes

- [x] rename Mining Tenements - WA Mining tenements and move to Mining section

- [x] Keep the 3 bottom layers: Petroleum pipelines, releases and titles

**Comment by AnaBelgun** [comment]
[Wave Atlas intro and use guide.txt](https://github.com/TerriaJS/NorthernAustralia/files/2007200/Wave.Atlas.intro.and.use.guide.txt)

**Comment by meh9** [comment]
Merged in #94
